<?php require_once 'config.php'; require_login(); $pdo = db(); $uid = $_SESSION['user']['id'];
$stmt=$pdo->prepare('SELECT dt.id daily_id,t.*,s.id submission_id,s.status,s.description FROM daily_tasks dt JOIN tasks t ON t.id=dt.task_id LEFT JOIN submissions s ON s.daily_task_id=dt.id WHERE dt.user_id=? AND dt.assigned_on=CURDATE()'); $stmt->execute([$uid]); $quest=$stmt->fetch();
if (!$quest) { $task=$pdo->query('SELECT id FROM tasks WHERE active=1 ORDER BY RAND() LIMIT 1')->fetch(); $pdo->prepare('INSERT INTO daily_tasks(user_id,task_id,assigned_on) VALUES (?,?,CURDATE())')->execute([$uid,$task['id']]); redirect('dashboard.php'); }
$badges=$pdo->prepare('SELECT b.* FROM user_badges ub JOIN badges b ON b.id=ub.badge_id WHERE ub.user_id=? ORDER BY b.threshold');$badges->execute([$uid]);$badges=$badges->fetchAll();
$recent=$pdo->prepare('SELECT t.title,t.icon,s.status,s.submitted_at FROM submissions s JOIN daily_tasks dt ON dt.id=s.daily_task_id JOIN tasks t ON t.id=dt.task_id WHERE dt.user_id=? ORDER BY s.submitted_at DESC LIMIT 4');$recent->execute([$uid]);$recent=$recent->fetchAll(); require 'header.php'; $u=$_SESSION['user']; ?>
<section class="dashboard-head"><div><p class="eyebrow">Good <?= date('H') < 12 ? 'morning' : (date('H') < 18 ? 'afternoon' : 'evening') ?>, <?= esc(explode(' ', $u['name'])[0]) ?></p><h1>Your next ripple starts here.</h1></div><div class="point-pill"><span>✦</span><b><?= (int)$u['points'] ?></b> points</div></section>
<section class="quest-layout"><article class="today-card"><div class="card-label">Today’s positive quest <span><?= date('D, M j') ?></span></div><div class="quest-icon"><?= esc($quest['icon']) ?></div><p class="tag"><?= esc($quest['category']) ?></p><h2><?= esc($quest['title']) ?></h2><p><?= esc($quest['description']) ?></p><div class="quest-bottom"><span>✦ <?= (int)$quest['points'] ?> points</span><?php if (!$quest['submission_id']): ?><a class="button" href="submit.php">I did this! <span>→</span></a><?php elseif ($quest['status']==='pending'): ?><span class="status pending">Under review</span><?php elseif ($quest['status']==='approved'): ?><span class="status approved">✓ Approved</span><?php else: ?><a class="button secondary" href="submit.php">Try again</a><?php endif; ?></div></article>
<aside class="streak-card"><div class="flame">🔥</div><p>Current streak</p><b><?= (int)$u['streak'] ?><small> days</small></b><div class="streak-bar"><span style="width:<?= min(100, ($u['streak'] % 7) * 14.28) ?>%"></span></div><p class="subtle">Your best: <?= (int)$u['longest_streak'] ?> days</p></aside></section>
<section class="lower-grid"><article class="panel"><div class="panel-title"><div><p class="eyebrow">Your collection</p><h2>Badges earned</h2></div><span><?= count($badges) ?> / 4</span></div><div class="badges"><?php foreach ($badges as $b): ?><div class="badge"><i><?= esc($b['icon']) ?></i><b><?= esc($b['name']) ?></b><small><?= esc($b['description']) ?></small></div><?php endforeach; if (!$badges): ?><p class="empty">Complete your first quest to unlock a badge.</p><?php endif; ?></div></article><article class="panel activity"><div class="panel-title"><div><p class="eyebrow">Your impact</p><h2>Recent activity</h2></div></div><?php foreach ($recent as $r): ?><div class="activity-row"><i><?= esc($r['icon']) ?></i><span><b><?= esc($r['title']) ?></b><small><?= date('M j',strtotime($r['submitted_at'])) ?></small></span><em class="status <?= esc($r['status']) ?>"><?= esc($r['status']) ?></em></div><?php endforeach; if (!$recent): ?><p class="empty">Your completed quests will appear here.</p><?php endif; ?></article></section>
<?php require 'footer.php'; ?>
